export type Country = {
  countryCode: string;
  id: string;
  name: string;
  region: string;
  regionCode: string;
  subRegionCode: string;
  alpha2?: string;
  alpha3?: string;
  intermediateRegion?: string;
  intermediateRegionCode?: string;
  subRegion?: string;
};

export type Countries = {
  [key: string]: Country;
};

export const COUNTRIES_MAP: Countries = {
  AD: {
    countryCode: '020',
    id: 'AD',
    name: 'Andorra',
    region: 'Europe',
    regionCode: '150',
    subRegionCode: '039',
  },
  AE: {
    countryCode: '784',
    id: 'AE',
    name: 'United Arab Emirates',
    region: 'Asia',
    regionCode: '142',
    subRegionCode: '145',
  },
  AF: {
    countryCode: '004',
    id: 'AF',
    name: 'Afghanistan',
    region: 'Asia',
    regionCode: '142',
    subRegionCode: '034',
  },
  AG: {
    countryCode: '028',
    id: 'AG',
    name: 'Antigua and Barbuda',
    region: 'Americas',
    regionCode: '019',
    subRegionCode: '419',
  },
  AI: {
    countryCode: '660',
    id: 'AI',
    name: 'Anguilla',
    region: 'Americas',
    regionCode: '019',
    subRegionCode: '419',
  },
  AL: {
    countryCode: '008',
    id: 'AL',
    name: 'Albania',
    region: 'Europe',
    regionCode: '150',
    subRegionCode: '039',
  },
  AM: {
    countryCode: '051',
    id: 'AM',
    name: 'Armenia',
    region: 'Asia',
    regionCode: '142',
    subRegionCode: '145',
  },
  AO: {
    countryCode: '024',
    id: 'AO',
    name: 'Angola',
    region: 'Africa',
    regionCode: '002',
    subRegionCode: '202',
  },
  AQ: {
    countryCode: '010',
    id: 'AQ',
    name: 'Antarctica',
    region: '',
    regionCode: '',
    subRegionCode: '',
  },
  AR: {
    countryCode: '032',
    id: 'AR',
    name: 'Argentina',
    region: 'Americas',
    regionCode: '019',
    subRegionCode: '419',
  },
  AS: {
    countryCode: '016',
    id: 'AS',
    name: 'American Samoa',
    region: 'Oceania',
    regionCode: '009',
    subRegionCode: '061',
  },
  AT: {
    countryCode: '040',
    id: 'AT',
    name: 'Austria',
    region: 'Europe',
    regionCode: '150',
    subRegionCode: '155',
  },
  AU: {
    countryCode: '036',
    id: 'AU',
    name: 'Australia',
    region: 'Oceania',
    regionCode: '009',
    subRegionCode: '061',
  },
  AW: {
    countryCode: '533',
    id: 'AW',
    name: 'Aruba',
    region: 'Americas',
    regionCode: '019',
    subRegionCode: '419',
  },
  AX: {
    countryCode: '248',
    id: 'AX',
    name: 'Åland Islands',
    region: 'Europe',
    regionCode: '150',
    subRegionCode: '154',
  },
  AZ: {
    countryCode: '031',
    id: 'AZ',
    name: 'Azerbaijan',
    region: 'Asia',
    regionCode: '142',
    subRegionCode: '145',
  },
  BA: {
    countryCode: '070',
    id: 'BA',
    name: 'Bosnia and Herzegovina',
    region: 'Europe',
    regionCode: '150',
    subRegionCode: '039',
  },
  BB: {
    countryCode: '052',
    id: 'BB',
    name: 'Barbados',
    region: 'Americas',
    regionCode: '019',
    subRegionCode: '419',
  },
  BD: {
    countryCode: '050',
    id: 'BD',
    name: 'Bangladesh',
    region: 'Asia',
    regionCode: '142',
    subRegionCode: '034',
  },
  BE: {
    countryCode: '056',
    id: 'BE',
    name: 'Belgium',
    region: 'Europe',
    regionCode: '150',
    subRegionCode: '155',
  },
  BF: {
    countryCode: '854',
    id: 'BF',
    name: 'Burkina Faso',
    region: 'Africa',
    regionCode: '002',
    subRegionCode: '202',
  },
  BG: {
    countryCode: '100',
    id: 'BG',
    name: 'Bulgaria',
    region: 'Europe',
    regionCode: '150',
    subRegionCode: '151',
  },
  BH: {
    countryCode: '048',
    id: 'BH',
    name: 'Bahrain',
    region: 'Asia',
    regionCode: '142',
    subRegionCode: '145',
  },
  BI: {
    countryCode: '108',
    id: 'BI',
    name: 'Burundi',
    region: 'Africa',
    regionCode: '002',
    subRegionCode: '202',
  },
  BJ: {
    countryCode: '204',
    id: 'BJ',
    name: 'Benin',
    region: 'Africa',
    regionCode: '002',
    subRegionCode: '202',
  },
  BL: {
    countryCode: '652',
    id: 'BL',
    name: 'Saint Barthélemy',
    region: 'Americas',
    regionCode: '019',
    subRegionCode: '419',
  },
  BM: {
    countryCode: '060',
    id: 'BM',
    name: 'Bermuda',
    region: 'Americas',
    regionCode: '019',
    subRegionCode: '021',
  },
  BN: {
    countryCode: '096',
    id: 'BN',
    name: 'Brunei Darussalam',
    region: 'Asia',
    regionCode: '142',
    subRegionCode: '035',
  },
  BO: {
    countryCode: '068',
    id: 'BO',
    name: 'Bolivia (Plurinational State of)',
    region: 'Americas',
    regionCode: '019',
    subRegionCode: '419',
  },
  BQ: {
    countryCode: '535',
    id: 'BQ',
    name: 'Bonaire, Sint Eustatius and Saba',
    region: 'Americas',
    regionCode: '019',
    subRegionCode: '419',
  },
  BR: {
    countryCode: '076',
    id: 'BR',
    name: 'Brazil',
    region: 'Americas',
    regionCode: '019',
    subRegionCode: '419',
  },
  BS: {
    countryCode: '044',
    id: 'BS',
    name: 'Bahamas',
    region: 'Americas',
    regionCode: '019',
    subRegionCode: '419',
  },
  BT: {
    countryCode: '064',
    id: 'BT',
    name: 'Bhutan',
    region: 'Asia',
    regionCode: '142',
    subRegionCode: '034',
  },
  BV: {
    countryCode: '074',
    id: 'BV',
    name: 'Bouvet Island',
    region: 'Americas',
    regionCode: '019',
    subRegionCode: '419',
  },
  BW: {
    countryCode: '072',
    id: 'BW',
    name: 'Botswana',
    region: 'Africa',
    regionCode: '002',
    subRegionCode: '202',
  },
  BY: {
    countryCode: '112',
    id: 'BY',
    name: 'Belarus',
    region: 'Europe',
    regionCode: '150',
    subRegionCode: '151',
  },
  BZ: {
    countryCode: '084',
    id: 'BZ',
    name: 'Belize',
    region: 'Americas',
    regionCode: '019',
    subRegionCode: '419',
  },
  CA: {
    countryCode: '124',
    id: 'CA',
    name: 'Canada',
    region: 'Americas',
    regionCode: '019',
    subRegionCode: '021',
  },
  US: {
    countryCode: '840',
    id: 'US',
    name: 'United States of America',
    region: 'Americas',
    regionCode: '019',
    subRegionCode: '021',
  },
  UY: {
    countryCode: '858',
    id: 'UY',
    name: 'Uruguay',
    region: 'Americas',
    regionCode: '019',
    subRegionCode: '419',
  },
  UZ: {
    countryCode: '860',
    id: 'UZ',
    name: 'Uzbekistan',
    region: 'Asia',
    regionCode: '142',
    subRegionCode: '143',
  },
  VA: {
    countryCode: '336',
    id: 'VA',
    name: 'Holy See',
    region: 'Europe',
    regionCode: '150',
    subRegionCode: '039',
  },
  VC: {
    countryCode: '670',
    id: 'VC',
    name: 'Saint Vincent and the Grenadines',
    region: 'Americas',
    regionCode: '019',
    subRegionCode: '419',
  },
  VE: {
    countryCode: '862',
    id: 'VE',
    name: 'Venezuela (Bolivarian Republic of)',
    region: 'Americas',
    regionCode: '019',
    subRegionCode: '419',
  },
  VG: {
    countryCode: '092',
    id: 'VG',
    name: 'Virgin Islands (British)',
    region: 'Americas',
    regionCode: '019',
    subRegionCode: '419',
  },
  VI: {
    countryCode: '850',
    id: 'VI',
    name: 'Virgin Islands (U.S.)',
    region: 'Americas',
    regionCode: '019',
    subRegionCode: '419',
  },
  VN: {
    countryCode: '704',
    id: 'VN',
    name: 'Viet Nam',
    region: 'Asia',
    regionCode: '142',
    subRegionCode: '035',
  },
  VU: {
    countryCode: '548',
    id: 'VU',
    name: 'Vanuatu',
    region: 'Oceania',
    regionCode: '009',
    subRegionCode: '061',
  },
  WF: {
    countryCode: '876',
    id: 'WF',
    name: 'Wallis and Futuna',
    region: 'Oceania',
    regionCode: '009',
    subRegionCode: '061',
  },
  WS: {
    countryCode: '882',
    id: 'WS',
    name: 'Samoa',
    region: 'Oceania',
    regionCode: '009',
    subRegionCode: '061',
  },
  YE: {
    countryCode: '887',
    id: 'YE',
    name: 'Yemen',
    region: 'Asia',
    regionCode: '142',
    subRegionCode: '145',
  },
  YT: {
    countryCode: '175',
    id: 'YT',
    name: 'Mayotte',
    region: 'Africa',
    regionCode: '002',
    subRegionCode: '202',
  },
  ZA: {
    countryCode: '710',
    id: 'ZA',
    name: 'South Africa',
    region: 'Africa',
    regionCode: '002',
    subRegionCode: '202',
  },
  ZM: {
    countryCode: '894',
    id: 'ZM',
    name: 'Zambia',
    region: 'Africa',
    regionCode: '002',
    subRegionCode: '202',
  },
  ZW: {
    countryCode: '716',
    id: 'ZW',
    name: 'Zimbabwe',
    region: 'Africa',
    regionCode: '002',
    subRegionCode: '202',
  },
};

export const COUNTRIES = Object.values(COUNTRIES_MAP);
